export const START_DRAWING = "START_DRAWING";
export const STOP_DRAWING = "STOP_DRAWING";
export const CHANGE_COLOR = "CHANGE_COLOR";
export const CHANGE_PENCIL_SIZE = "CHANGE_PENCIL_SIZE";
export const CHANGE_PENCIL_CAP = "CHANGE_PENCIL_CAP";
export const ACTIVATE_ERASER = "ACTIVATE_ERASER";
export const ACTIVATE_MOBILE_RESPONSIVE = "ACTIVATE_MOBILE_RESPONSIVE";
export const ACTIVATE_MOBILE_NAV = "ACTIVATE_MOBILE_NAV";
